### ISSUE TITLE
Registration email activation link redirects to localhost

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/epi-lab-server#1]
The activation link in the email a user receives following a registration request redirects to localhost.
It should redirect to the proper server address.

**Comment by birgitlewicki** [comment]
The node server needs to run in either development (default) or production mode to get the correct environment configs. Currently the node server was running in development mode on epilab.bfr.berlin.
Starting the node server in production mode:
> NODE_ENV=production node server.js
