### ISSUE TITLE
Typing and executing url in browser throws backend error

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/epi-lab-server#9]
Typing e.g. the url

http://localhost:4200/users/login

in the browser's address bar and executing the request does not load the page and throws the backend error

Error: ENOENT: no such file or directory, stat '/mnt/data/projects/workspace/epilab/epi-lab-server/dist/dist/index.html'

This should load/reload the corresponding page in the browser.

**Comment by dptolle** [comment]
@birgitlewicki In which environment did this bug manifest itself?  Local developer build? It doesn't appear to occur on the Test server.

**Comment by birgitlewicki** [comment]
The bug occurred in the deployment environment and is disappeared now.
Closing.
